on:
  # Build every pull request, to check for regressions.
  pull_request:

  # Build when a PR is merged, to update the README's CI badge.
  push:

name: build

env:
      CONFIG: --enable-benchmarks --enable-documentation --enable-tests --haddock-all --haddock-hyperlink-source --haddock-internal

defaults:
  run:
    shell: bash

jobs:

  # Run hlint and fourmolu (bin/lint.sh --check) to check for code improvements and formatting
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.9.1
        name: Setup Haskell
        with:
          ghc-version:   '9.6.7'
          cabal-version: latest
      - uses: actions/cache@v4
        name: caching lint tools
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-lint-${{ hashFiles('validation.cabal', 'cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-cabal-lint-
      - run: cabal update
      - run: cabal install hlint-3.8 --install-method=copy --overwrite-policy=always
      - run: cabal install fourmolu-0.15.0.0 --install-method=copy --overwrite-policy=always
      - run: bin/lint.sh --check


  # Check that the project builds with the specified lower bounds.
  lower-bounds:
    env:
      CONSTRAINTS: --project-file=lower-bounds.project
    name: Lower Bounds Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.9.1
        name: Setup Haskell
        with:
          cabal-version: latest
          ghc-version:   9.6.7

      - run: cabal update
      - run: cabal clean
      - run: cabal configure $CONFIG $CONSTRAINTS
      - run: cabal freeze    $CONFIG $CONSTRAINTS
      - uses: actions/cache@v4
        name: caching lower bounds check
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-lower-bounds-${{ hashFiles('lower-bounds.project.freeze') }}

      - run: cabal build     $CONFIG $CONSTRAINTS --only-dependencies
      - run: cabal build     $CONFIG $CONSTRAINTS
      - run: cabal test      hedgehog $CONSTRAINTS


  # Run the hedgehog and doctest test suites.
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.9.1
        name: Setup Haskell
        with:
          cabal-version: latest
          ghc-version:   9.6.7

      - run: cabal update
      - run: cabal clean
      - run: cabal configure --enable-tests --with-compiler=ghc
      - run: cabal freeze    --enable-tests
      - uses: actions/cache@v4
        name: caching unit tests
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-tests-${{ hashFiles('cabal.project.freeze') }}

      # The doctest suite runs the doctest executable, which must be built with the same GHC.
      - run: cabal install doctest --install-method=copy --overwrite-policy=always
      - run: cabal test


  # Cabal build matrix
  cabal-build-matrix:
    name: GHC-${{ matrix.ghc }}, cabal${{matrix.cabal}}, ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc:   [ '9.6.7', '9.8.4', '9.10.3' ]
        cabal: [ latest ]
        os:    [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.9.1
        name: Setup Haskell
        with:
          ghc-version:   ${{ matrix.ghc   }}
          cabal-version: ${{ matrix.cabal }}
      - run: gcc    --version
      - run: g++    --version
      - run: ghc    --version
      - run: cabal update
      - run: cabal clean
      - run: cabal configure $CONFIG --with-compiler=ghc
      - run: cabal freeze    $CONFIG
      - uses: actions/cache@v4
        name: windows caching
        with:
          path: |
            c:\sr
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          # restore keys is a fall back when the freeze plan is different
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
        if:  matrix.os == 'windows-latest'
      - uses: actions/cache@v4
        name: ubuntu-linux and osx caching
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          # restore keys is a fall back when the freeze plan is different
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
        if:  matrix.os != 'windows-latest'
      - run: cabal build --only-dependencies
      - run: cabal build $CONFIG
